kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/azure-lab-container
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]azure-lab-container.<guid>.<region>.aksapp.io
      - $(spacePrefix)azure-lab-container$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true