version: '3.3'
services:
  back:
    build: back/
    ports:
      - "5581:80"
    container_name: back
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
  front:
    build: front/
    ports:
      - "5580:80"
    container_name: front
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
